require 'exifr'

require 'routes/root'
require 'routes/login'
require 'routes/upload'
require 'routes/assets'
require 'routes/favorites'
require 'routes/search'
require 'routes/albums'
require 'routes/summary'
require 'routes/rebecca'
